//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DisposalList
    {
        public Nullable<long> No { get; set; }
        public string NoDisposal { get; set; }
        public string PIC { get; set; }
        public string LOB { get; set; }
        public string Lokasi { get; set; }
        public string AlasanLelang { get; set; }
        public string Status { get; set; }
    }
}
